platform :ios, '11.0'

target 'MongoDBSample' do
  use_frameworks!

  pod 'FacebookLogin'
  pod 'Firebase'
  pod 'GoogleSignIn'
  pod 'StitchCore', '~> 4.0.0-beta-1'
  pod 'StitchRemoteMongoDBService', '~> 4.0.0-beta-1'
end
