export const Localization = {
  HEADER: {
    TITLE: "platespace",
    SUB_TITLE: "FIND RESTAURANTS NEAR YOU",
    FILTER_TITLE: "FILTERED BY:",
    EDIT_BUTTON_TEXT: "EDIT",
    NO_FILTER: "NO FILTER SELECTED",
    LOG_OUT: "LOG OUT"
  },
  REVIEW_DIALOG: {
    TITLE_EDIT: "EDIT REVIEW",
    TITLE_ADD: "ADD REVIEW",
    BUTTON_TEXT_EDIT: "OK",
    BUTTON_TEXT_POST: "POST",
    BUTTON_TEXT_OK: "OK",
    INPUT_PLACEHOLDER: "WRITE SOMETHING...",
    RATE_TITLE: "RATE NOW",
    ATTENTION:
      "YOU SHOULD LOG IN TO PLATESPACE IN ORDER TO ADD A REVIEW AND RATE THIS RESTAURANT",
    VALIDATION_TEXT: "Please make sure to add a review or to rate",
    IMAGE_UPLOAD_TEXT:
      "Try dropping one image here, or click to select an image to upload."
  },
  AUTHENTICATION_FORM: {
    EMAIL_PLACEHOLDER: "EMAIL",
    PASSWORD_PLACEHOLDER: "PASSWORD",
    BUTTON_LOGIN_FB_TEXT: "CONTINUE WITH FACEBOOK",
    SUBTEXT: "PLATESPACE REQUIRES ACCESS TO YOUR LOCATION",
    OR: "OR",
    BUTTON_TEXT: "OK",
    TITLE: "AUTHENTICATION FORM",
    NAVIGATION_BUTTON_TEXT: "CONTINUE",
    NAVIGATION_MESSAGE: "NAVIGATE",
    SKIP_BUTTON: "SKIP"
  },
  LOGIN_FORM: {
    BUTTON_TEXT: "LOG IN",
    TITLE: "LOGIN",
    NAVIGATION_BUTTON_TEXT: "CREATE",
    NAVIGATION_MESSAGE: "DON'T HAVE AN ACCOUNT?"
  },
  CREATE_FORM: {
    BUTTON_TEXT: "CREATE",
    TITLE: "CREATE NEW ACCOUNT",
    NAVIGATION_BUTTON_TEXT: "LOG IN",
    NAVIGATION_MESSAGE: "ALREADY HAVE AN ACCOUNT?"
  },
  CONFIRM_FORM: {
    BUTTON_TEXT: "CONFIRM",
    TITLE: "EMAIL CONFIRMATION",
    CONFIRMED: "YOUR ACCOUNT IS CONFIRMED! YOU CAN SIGN IN NOW"
  },
  SEARCH_COMPONENT: {
    INPUT_PLACEHOLDER: "RESTAURANT NAME",
    BUTTON_TEXT: "SEARCH"
  },
  FILTER_DIALOG: {
    TITLE: "FILTER",
    OK_BUTTON_TEXT: "APPLY"
  },
  FILTERS: {
    WIFI: "HAS WiFi",
    OPEN_ON_WEEKENDS: "OPEN ON WEEKENDS",
    PARKING: "FREE PARKING",
    VEGETARIAN: "VEGAN FRIENDLY"
  },
  SUB_HEADER: {
    TITLE: "RESTAURANTS NEAR YOU",
    MAP_BUTTON_LABEL: "VIEW AS LIST",
    LIST_BUTTON_LABEL: "VIEW ON MAP"
  },
  RESTAURANT_INFO: {
    ADDRESS: "Address",
    PHONE: "Phone",
    WEB: "Web",
    OPEN_HOURS: "Open Hours"
  },
  REVIEWS_HEADER: {
    TITLE: "Reviews",
    BUTTON_TEXT: "ADD"
  },
  REVIEW_ITEM: {
    EDIT_BUTTON_TEXT: "EDIT"
  },
  AUTHENTICATION_HEADER: {
    TITLE: "PLATESPACE",
    SUB_TITLE: "FIND RESTAURANTS NEAR YOU"
  },
  RESTAURANT_LIST_RESULTS: {
    NO_RESULTS_LABEL: "NO RESULTS FOUND"
  },
  CREATE_ACCOUNT: {
    TITLE: "CREATE ACCOUNT",
    TEXT: "ACCOUNT CREATED",
    BUTTON: "OK"
  },
  CONFIRM_ACCOUNT: {
    TITLE: "ACCOUNT CONFIRMED",
    TEXT: "YOU CAN SIGN IN NOW WITH YOUR NEW CREDENTIALS",
    BUTTON: "OK"
  },
  ERRORS: {
    TITLE: "ERROR",
    CREATE_ACCOUNT: "AN ERROR OCCURRED WHILE CREATING YOUR ACCOUNT",
    CONFIRM_ACCOUNT: "WE APOLOGIZE YOUR ACCOUNT COULD NOT BE CONFIRMED",
    BUTTON: "OK",
    FAILED_LOGIN: "COULD NOT LOG IN"
  },
  RESTAURANT_DETAILS: {
    NO_REVIEWS_LABEL: "NO REVIEWS"
  }
};
